apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-debug-shell
  namespace: da-mmsa-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: msa-debug-shell
  template:
    metadata:
      labels:
        name: msa-debug-shell
    spec:
      containers:
        - name: msa-debug-shell
          image: noliveira87/msa-debug-shell:1.0.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "20Mi"
              cpu: "2m"
            limits:
              memory: "1Gi"
              cpu: "10m"
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            seccompProfile:
              type: RuntimeDefault
